from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField, SelectMultipleField, DecimalField, validators
from wtforms.validators import DataRequired, Length, Email, EqualTo
from wtforms.fields.html5 import DateField, IntegerField


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=2, max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Log In')


class TotalTuplesForm(FlaskForm):
    submit = SubmitField("Count Tuples")

class QueryOneForm(FlaskForm):
    counties = SelectMultipleField('Counties', [validators.required()], choices = [
        ('Alachua', 'Alachua'),
        ('Baker', 'Baker'),
        ('Bay', 'Bay'),
        ('Bradford', 'Bradford'),
        ('Brevard', 'Brevard'),
        ('Broward', 'Broward'),
        ('Calhoun', 'Calhoun'),
        ('Charlotte', 'Charlotte'),
        ('Citrus', 'Citrus'),
        ('Clay', 'Clay'),
        ('Collier', 'Collier'),
        ('Columbia', 'Columbia'),
        ('De Soto', 'De Soto'),
        ('Dixie', 'Dixie'),
        ('Duval', 'Duval'),
        ('Escambia', 'Escambia'),
        ('Flagler', 'Flagler'),
        ('Franklin', 'Franklin'),
        ('Gadsden', 'Gadsden'),
        ('Gilchrist', 'Gilchrist'),
        ('Glades', 'Glades'),
        ('Gulf', 'Gulf'),
        ('Hamilton', 'Hamilton'),
        ('Hardee', 'Hardee'),
        ('Hendry', 'Hendry'),
        ('Hernando', 'Hernando'),
        ('Highlands', 'Highlands'),
        ('Hillsborough', 'Hillsborough'),
        ('Holmes', 'Holmes'),
        ('Indian River', 'Indian River'),
        ('Jackson', 'Jackson'),
        ('Jefferson', 'Jefferson'),
        ('Lafayette', 'Lafayette'),
        ('Lake', 'Lake'),
        ('Lee', 'Lee'),
        ('Leon', 'Leon'),
        ('Levy', 'Levy'),
        ('Liberty', 'Liberty'),
        ('Madison', 'Madison'),
        ('Manatee', 'Manatee'),
        ('Marion', 'Marion'),
        ('Martin', 'Martin'),
        ('Miami-Dade', 'Miami - Dade'),
        ('Monroe', 'Monroe'),
        ('Nassau', 'Nassau'),
        ('Okaloosa', 'Okaloosa'),
        ('Okeechobee', 'Okeechobee'),
        ('Orange', 'Orange'),
        ('Osceola', 'Osceola'),
        ('Palm Beach', 'Palm Beach'),
        ('Pasco', 'Pasco'),
        ('Pinellas', 'Pinellas'),
        ('Polk', 'Polk'),
        ('Putnam', 'Putnam'),
        ('St Johns', 'St Johns'),
        ('St Lucie', 'St Lucie'),
        ('Santa Rosa', 'Santa Rosa'),
        ('Sarasota', 'Sarasota'),
        ('Seminole', 'Seminole'),
        ('Sumter', 'Sumter'),
        ('Suwannee', 'Suwannee'),
        ('Taylor', 'Taylor'),
        ('Union', 'Union'),
        ('Volusia', 'Volusia'),
        ('Wakulla', 'Wakulla'),
        ('Walton', 'Walton'),
        ('Washington', 'Washington')])
    dStart = DateField('Date Start (optional)', [validators.optional()], format='%Y-%m-%d')
    dEnd = DateField('Date End (optional)', [validators.optional()], format='%Y-%m-%d')
    submit = SubmitField('Submit')

# TODO put constraints on the date start and end date
class QueryTwoForm(FlaskForm):
    county = SelectField('County', [validators.required()], choices = [
        ('001', 'Alachua'),
        ('003', 'Baker'),
        ('005', 'Bay'),
        ('007', 'Bradford'),
        ('009', 'Brevard'),
        ('011', 'Broward'),
        ('013', 'Calhoun'),
        ('015', 'Charlotte'),
        ('017', 'Citrus'),
        ('019', 'Clay'),
        ('021', 'Collier'),
        ('023', 'Columbia'),
        ('027', 'De Soto'),
        ('029', 'Dixie'),
        ('031', 'Duval'),
        ('033', 'Escambia'),
        ('035', 'Flagler'),
        ('037', 'Franklin'),
        ('039', 'Gadsden'),
        ('041', 'Gilchrist'),
        ('043', 'Glades'),
        ('045', 'Gulf'),
        ('047', 'Hamilton'),
        ('049', 'Hardee'),
        ('051', 'Hendry'),
        ('053', 'Hernando'),
        ('055', 'Highlands'),
        ('057', 'Hillsborough'),
        ('059', 'Holmes'),
        ('061', 'Indian River'),
        ('063', 'Jackson'),
        ('065', 'Jefferson'),
        ('067', 'Lafayette'),
        ('069', 'Lake'),
        ('071', 'Lee'),
        ('073', 'Leon'),
        ('075', 'Levy'),
        ('077', 'Liberty'),
        ('079', 'Madison'),
        ('081', 'Manatee'),
        ('083', 'Marion'),
        ('085', 'Martin'),
        ('086', 'Miami-Dade'),
        ('087', 'Monroe'),
        ('089', 'Nassau'),
        ('091', 'Okaloosa'),
        ('093', 'Okeechobee'),
        ('095', 'Orange'),
        ('097', 'Osceola'),
        ('099', 'Palm Beach'),
        ('101', 'Pasco'),
        ('103', 'Pinellas'),
        ('105', 'Polk'),
        ('107', 'Putnam'),
        ('109', 'St Johns'),
        ('111', 'St Lucie'),
        ('113', 'Santa Rosa'),
        ('115', 'Sarasota'),
        ('117', 'Seminole'),
        ('119', 'Sumter'),
        ('121', 'Suwannee'),
        ('123', 'Taylor'),
        ('125', 'Union'),
        ('127', 'Volusia'),
        ('129', 'Wakulla'),
        ('131', 'Walton'),
        ('133', 'Washingto')])
    ethnicities = SelectMultipleField('Ethnicities', [validators.required()], choices = [
        ('1', 'White including Hispanic'),
        ('2', 'Black including Hispanic'),
        ('3', 'Asian/Pacific Islander including Hispanic'),
        ('4', 'American Indian/Alaskan Native including Hispanic'),
        ('5', 'Hispanic All Races'),
        ('6', 'All Non-White Races including Hispanic'),
        ('7', 'Other including Hispanic')])
    dStart = DateField('Date Start (optional)', [validators.optional()], format='%Y-%m-%d')
    dEnd = DateField('Date End (optional)', [validators.optional()], format='%Y-%m-%d')
    submit = SubmitField('Submit')

class QueryThreeForm(FlaskForm):
    counties = SelectMultipleField('Counties', [validators.required()], choices = [
        ('Alachua', 'Alachua'),
        ('Baker', 'Baker'),
        ('Bay', 'Bay'),
        ('Bradford', 'Bradford'),
        ('Brevard', 'Brevard'),
        ('Broward', 'Broward'),
        ('Calhoun', 'Calhoun'),
        ('Charlotte', 'Charlotte'),
        ('Citrus', 'Citrus'),
        ('Clay', 'Clay'),
        ('Collier', 'Collier'),
        ('Columbia', 'Columbia'),
        ('De Soto', 'De Soto'),
        ('Dixie', 'Dixie'),
        ('Duval', 'Duval'),
        ('Escambia', 'Escambia'),
        ('Flagler', 'Flagler'),
        ('Franklin', 'Franklin'),
        ('Gadsden', 'Gadsden'),
        ('Gilchrist', 'Gilchrist'),
        ('Glades', 'Glades'),
        ('Gulf', 'Gulf'),
        ('Hamilton', 'Hamilton'),
        ('Hardee', 'Hardee'),
        ('Hendry', 'Hendry'),
        ('Hernando', 'Hernando'),
        ('Highlands', 'Highlands'),
        ('Hillsborough', 'Hillsborough'),
        ('Holmes', 'Holmes'),
        ('Indian River', 'Indian River'),
        ('Jackson', 'Jackson'),
        ('Jefferson', 'Jefferson'),
        ('Lafayette', 'Lafayette'),
        ('Lake', 'Lake'),
        ('Lee', 'Lee'),
        ('Leon', 'Leon'),
        ('Levy', 'Levy'),
        ('Liberty', 'Liberty'),
        ('Madison', 'Madison'),
        ('Manatee', 'Manatee'),
        ('Marion', 'Marion'),
        ('Martin', 'Martin'),
        ('Miami-Dade', 'Miami - Dade'),
        ('Monroe', 'Monroe'),
        ('Nassau', 'Nassau'),
        ('Okaloosa', 'Okaloosa'),
        ('Okeechobee', 'Okeechobee'),
        ('Orange', 'Orange'),
        ('Osceola', 'Osceola'),
        ('Palm Beach', 'Palm Beach'),
        ('Pasco', 'Pasco'),
        ('Pinellas', 'Pinellas'),
        ('Polk', 'Polk'),
        ('Putnam', 'Putnam'),
        ('St Johns', 'St Johns'),
        ('St Lucie', 'St Lucie'),
        ('Santa Rosa', 'Santa Rosa'),
        ('Sarasota', 'Sarasota'),
        ('Seminole', 'Seminole'),
        ('Sumter', 'Sumter'),
        ('Suwannee', 'Suwannee'),
        ('Taylor', 'Taylor'),
        ('Union', 'Union'),
        ('Volusia', 'Volusia'),
        ('Wakulla', 'Wakulla'),
        ('Walton', 'Walton'),
        ('Washington', 'Washington')])
    dStart = DateField('Date Start (optional)', [validators.optional()], format='%Y-%m-%d')
    dEnd = DateField('Date End (optional)', [validators.optional()], format='%Y-%m-%d')
    threshold = DecimalField('Heat Value Threshold (optional)', [validators.optional()])
    submit = SubmitField('Submit')

class QueryFourForm(FlaskForm):
    counties = SelectMultipleField('Counties', [validators.required()], choices = [
        ('Alachua', 'Alachua'),
        ('Baker', 'Baker'),
        ('Bay', 'Bay'),
        ('Bradford', 'Bradford'),
        ('Brevard', 'Brevard'),
        ('Broward', 'Broward'),
        ('Calhoun', 'Calhoun'),
        ('Charlotte', 'Charlotte'),
        ('Citrus', 'Citrus'),
        ('Clay', 'Clay'),
        ('Collier', 'Collier'),
        ('Columbia', 'Columbia'),
        ('De Soto', 'De Soto'),
        ('Dixie', 'Dixie'),
        ('Duval', 'Duval'),
        ('Escambia', 'Escambia'),
        ('Flagler', 'Flagler'),
        ('Franklin', 'Franklin'),
        ('Gadsden', 'Gadsden'),
        ('Gilchrist', 'Gilchrist'),
        ('Glades', 'Glades'),
        ('Gulf', 'Gulf'),
        ('Hamilton', 'Hamilton'),
        ('Hardee', 'Hardee'),
        ('Hendry', 'Hendry'),
        ('Hernando', 'Hernando'),
        ('Highlands', 'Highlands'),
        ('Hillsborough', 'Hillsborough'),
        ('Holmes', 'Holmes'),
        ('Indian River', 'Indian River'),
        ('Jackson', 'Jackson'),
        ('Jefferson', 'Jefferson'),
        ('Lafayette', 'Lafayette'),
        ('Lake', 'Lake'),
        ('Lee', 'Lee'),
        ('Leon', 'Leon'),
        ('Levy', 'Levy'),
        ('Liberty', 'Liberty'),
        ('Madison', 'Madison'),
        ('Manatee', 'Manatee'),
        ('Marion', 'Marion'),
        ('Martin', 'Martin'),
        ('Miami-Dade', 'Miami - Dade'),
        ('Monroe', 'Monroe'),
        ('Nassau', 'Nassau'),
        ('Okaloosa', 'Okaloosa'),
        ('Okeechobee', 'Okeechobee'),
        ('Orange', 'Orange'),
        ('Osceola', 'Osceola'),
        ('Palm Beach', 'Palm Beach'),
        ('Pasco', 'Pasco'),
        ('Pinellas', 'Pinellas'),
        ('Polk', 'Polk'),
        ('Putnam', 'Putnam'),
        ('St Johns', 'St Johns'),
        ('St Lucie', 'St Lucie'),
        ('Santa Rosa', 'Santa Rosa'),
        ('Sarasota', 'Sarasota'),
        ('Seminole', 'Seminole'),
        ('Sumter', 'Sumter'),
        ('Suwannee', 'Suwannee'),
        ('Taylor', 'Taylor'),
        ('Union', 'Union'),
        ('Volusia', 'Volusia'),
        ('Wakulla', 'Wakulla'),
        ('Walton', 'Walton'),
        ('Washington', 'Washington')])
    dStart = IntegerField('Start Year (optional)', [validators.optional(), validators.NumberRange(min=2005, max=2016, message="Please input a value between %(min)s and %(max)s")])
    dEnd = IntegerField('End Year (optional)', [validators.optional(), validators.NumberRange(min=2005, max=2016, message="Please input a value between %(min)s and %(max)s")])
    submit = SubmitField('Submit')



class QueryFiveForm(FlaskForm):
    counties = SelectMultipleField('Counties', [validators.required()], choices = [
        ('Alachua', 'Alachua'),
        ('Baker', 'Baker'),
        ('Bay', 'Bay'),
        ('Bradford', 'Bradford'),
        ('Brevard', 'Brevard'),
        ('Broward', 'Broward'),
        ('Calhoun', 'Calhoun'),
        ('Charlotte', 'Charlotte'),
        ('Citrus', 'Citrus'),
        ('Clay', 'Clay'),
        ('Collier', 'Collier'),
        ('Columbia', 'Columbia'),
        ('De Soto', 'De Soto'),
        ('Dixie', 'Dixie'),
        ('Duval', 'Duval'),
        ('Escambia', 'Escambia'),
        ('Flagler', 'Flagler'),
        ('Franklin', 'Franklin'),
        ('Gadsden', 'Gadsden'),
        ('Gilchrist', 'Gilchrist'),
        ('Glades', 'Glades'),
        ('Gulf', 'Gulf'),
        ('Hamilton', 'Hamilton'),
        ('Hardee', 'Hardee'),
        ('Hendry', 'Hendry'),
        ('Hernando', 'Hernando'),
        ('Highlands', 'Highlands'),
        ('Hillsborough', 'Hillsborough'),
        ('Holmes', 'Holmes'),
        ('Indian River', 'Indian River'),
        ('Jackson', 'Jackson'),
        ('Jefferson', 'Jefferson'),
        ('Lafayette', 'Lafayette'),
        ('Lake', 'Lake'),
        ('Lee', 'Lee'),
        ('Leon', 'Leon'),
        ('Levy', 'Levy'),
        ('Liberty', 'Liberty'),
        ('Madison', 'Madison'),
        ('Manatee', 'Manatee'),
        ('Marion', 'Marion'),
        ('Martin', 'Martin'),
        ('Miami-Dade', 'Miami - Dade'),
        ('Monroe', 'Monroe'),
        ('Nassau', 'Nassau'),
        ('Okaloosa', 'Okaloosa'),
        ('Okeechobee', 'Okeechobee'),
        ('Orange', 'Orange'),
        ('Osceola', 'Osceola'),
        ('Palm Beach', 'Palm Beach'),
        ('Pasco', 'Pasco'),
        ('Pinellas', 'Pinellas'),
        ('Polk', 'Polk'),
        ('Putnam', 'Putnam'),
        ('St Johns', 'St Johns'),
        ('St Lucie', 'St Lucie'),
        ('Santa Rosa', 'Santa Rosa'),
        ('Sarasota', 'Sarasota'),
        ('Seminole', 'Seminole'),
        ('Sumter', 'Sumter'),
        ('Suwannee', 'Suwannee'),
        ('Taylor', 'Taylor'),
        ('Union', 'Union'),
        ('Volusia', 'Volusia'),
        ('Wakulla', 'Wakulla'),
        ('Walton', 'Walton'),
        ('Washington', 'Washington')])
    dStart = DateField('Date Start (optional)', [validators.optional()], format='%Y-%m-%d')
    dEnd = DateField('Date End (optional)', [validators.optional()], format='%Y-%m-%d')
    submit = SubmitField('Submit')